### ISSUE TITLE
Dialog not appearing where the marker is

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#79]
**Godot version**: 4.1.1
**Popochiu Version**: 2.0 alpha
**OS**: Windows 11

## Description of the issue
The dialogue text appears in a different position than where the **DialogPos** maker is placed

This is where my marker is (for testing purposes I've placed it right on the head):
![image](https://github.com/mapedorr/popochiu/assets/1595523/f27fabd0-edf3-478c-8bbb-8110befb5120)

But the text appears higher up:
![image](https://github.com/mapedorr/popochiu/assets/1595523/65df3be2-2fe8-4469-8010-1845af049f37)
![image](https://github.com/mapedorr/popochiu/assets/1595523/8ac24956-365f-4ac2-95ca-c617afe3bf50)

**Comment by papernoise** [comment]
Oh wait, I think I figured this one out. The marker does take the mouse icon into account doesn't it?

**Comment by mapedorr** [comment]
> Oh wait, I think I figured this one out. The marker does take the mouse icon into account doesn't it?

Yes, it does. But I think you're right, it shouldn't take the icon into account for placing the text.

**Comment by mapedorr** [comment]
I'll work on this since I'm currently working on #40

**Comment by mapedorr** [comment]
@papernoise In case you need it, in the link are the files that fix this. I'll put them there since my work on refactoring the GUI will take a couple of days to be ready to be merged into the 2.0 branch.

[Dialog text files](https://mega.nz/folder/WzoSzCwI#MlklVxAkPtmZoi3yMDEXkA)

You'll have to place them in: `addons/popochiu/engine/objects/graphic_interface/dialog_text/`

**Comment by papernoise** [comment]
cool thanks!

**Comment by mapedorr** [comment]
Fixed in 88044a2cf182f5b1b121749fde49e6e62640767c
